spring:
  application:
    name: NutritionTrackerBackend

  datasource:
    url: jdbc:postgresql://localhost:5436/carentry
    driver-class-name: org.postgresql.Driver
    username: carentry
    password: carentry1
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080