CREATE TABLE car
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    make    VARCHAR(255),
    model   VARCHAR(255),
    year    INTEGER                                 NOT NULL,
    price   DOUBLE PRECISION                        NOT NULL,
    is_used BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_car PRIMARY KEY (id)
);